#! /usr/bin/env ruby

require "byebug"

class Node
  def initialize(input)
    @node_count = input.next.to_i
    @meta_count  = input.next.to_i
    @nodes = []
    @meta = []
    @node_count.times do
      @nodes.push(Node.new(input))
    end
    @meta_count.times do
      @meta.push(input.next.to_i)
    end
  end
  def sum
    node_sum = @nodes.map {|node| node.sum}.reduce(:+)
    node_sum ||= 0
    @meta.reduce(:+) + node_sum
  end
end
input = File.readlines("./input2.txt").first.strip.split.each
node = Node.new(input)
puts node.sum
